# This file is based on templates provided and copyrighted by Autodesk, Inc.
# This file has been modified by Epic Games, Inc. and is subject to the license
# file included in this repository.

################################################################################

includes:
- ../frameworks.yml
- ../../app_locations.yml
- ../tk-unreal-location.yml
- ./tk-multi-loader2.yml
- ./tk-multi-publish2.yml
- ../../settings/tk-multi-screeningroom.yml
- ./tk-multi-shotgunpanel.yml

################################################################################

# asset_step
settings.tk-unreal.asset_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
  location: "@tk-unreal.location"
  menu_favourites: []
  run_at_startup: []
  launch_builtin_plugins: [basic]
  automatic_context_switch: false

# project
settings.tk-unreal.project:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-loader2: "@settings.tk-multi-loader2.unreal"
    tk-multi-publish2: "@settings.tk-multi-publish2.unreal.project"
    tk-multi-pythonconsole:
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.unreal"
  location: "@tk-unreal.location"
  menu_favourites: []
  run_at_startup:
  - {app_instance: tk-multi-shotgunpanel, name: ''}
  launch_builtin_plugins: [basic]
  automatic_context_switch: false
